### ISSUE TITLE
Collections not shown in phpstorm 2019.1

### ISSUE THREAD

**Issue by johndcarmichael** [dboissier/mongo4idea#270] opened 2019-05-03 11:39 UTC
The plugin will connect to the localhost
The plugin will display databases and collections in a list
When you double click a collection to view the documents nothing happens.

**Comment by aogashima95** [comment] 2019-05-15 09:55
Duplicate of #269

**Comment by dboissier** [comment] 2019-10-16 11:10
It seems to be ok (see #269)

**Closed by dboissier** 2019-10-16 11:10 UTC
