### ISSUE TITLE
Use private key auth for ssh connections

### ISSUE THREAD

**Issue by gpelelis** [dboissier/mongo4idea#196] opened 2017-04-11 10:30 UTC
Currently, the plugin supports only connections using a password on ssh. It would be nice if I can use an ssh key for authentication. 
Example of how this looks on [robomongo](https://robomongo.org/) app
![image](https://cloud.githubusercontent.com/assets/6285882/24904968/f5308772-1eba-11e7-9050-717c32fe2540.png)

**Comment by hgraca** [comment] 2017-08-25 07:30
This is a duplicate of #189

**Comment by dboissier** [comment] 2018-06-21 20:31
Hi,

I am almost done with the SSH private key feature. What behavior would you like to have ? Asking the passphrase each time you connect to the server or store it temporary (cleared whenever you quit IntelliJ) ?

**Comment by dboissier** [comment] 2018-06-27 05:16
Hi,

you will find a SNAPSHOT [here](https://github.com/dboissier/mongo4idea/raw/master/snapshot/mongo4idea-0.11-SNAPSHOT.zip)

**Closed** 2018-07-24 07:53 UTC
Labels: enhancement
